services:
  postgres:
    image: postgres:15.14-alpine
    container_name: etl-postgres
    environment:
      POSTGRES_DB: etl
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build:
        context: ..
        dockerfile: compose/Dockerfile
    container_name: etl-runner
#    depends_on:
#      - postgres
    environment:
      ETL_DATABASE_URL: postgresql+psycopg2://etl:etl@postgres:5432/etl
      ETL_CHUNK_SIZE: 1000
      ETL_TEMP_DIR: /data
      ETL_REQUEST_TIMEOUT: 1000
    volumes:
      - ../data:/data
      - ../src:/opt/app-root/src:rw
    # command: ["run", "--run-id=local-test"]
    tty: true
    # command: [ "tail", "-f", "/dev/null" ]
    command: [ "sleep", "infinity" ]

volumes:
  pgdata:
